version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp
    mode: 777
hooks:
  BeforeInstall:
    - location: deployment/stopApp.sh
      timeout: 60
  ApplicationStart:
    - location: deployment/startApp.sh
      timeout: 10