version: 0.0
os: linux
files:
  - source: /
    destination: /myapp
permissions:
  - object: /myapp/deployment/
    mode: 777
hooks:
  BeforeInstall:
    - location: deployment/stopApp.sh
      timeout: 15
      runas: root
  ApplicationStart:
    - location: deployment/startApp.sh
      timeout: 15
      runas: root
